I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script
    Eileen "Suhhh dude"
Exception: Sayer 'Eileen' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script
    Eileen "Suhhh dude"
  File "C:\Users\haley\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\haley\renpy-8.3.6-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\haley\renpy-8.3.6-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Eileen' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Otome Ongoing 1.0
Sat Mar  1 13:06:17 2025
